/**
 * GoTo API
 * The GoTo REST API allows for offering trips and searching for public transport trips.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FoundTrip { 
    kind?: FoundTrip.KindEnum;
    startTime?: Date;
    startLocation?: string;
    endTime?: Date;
    endLocation?: string;
}
export namespace FoundTrip {
    export type KindEnum = 0 | 1;
    export const KindEnum = {
        NUMBER_0: 0 as KindEnum,
        NUMBER_1: 1 as KindEnum
    };
}
